name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Asdqwe!23
          POSTGRES_DB: fastapi_users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready -U postgres
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait until PostgreSQL is ready
        run: |
          until pg_isready -h postgres -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: Create DB tables
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:Asdqwe!23@postgres:5432/fastapi_users
        run: python scripts/init_db.py

      - name: Run tests
        env:
          DATABASE_URL: postgresql+psycopg2://postgres:Asdqwe!23@postgres:5432/fastapi_users
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SECRET_KEY: your-super-secret-key
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build . -t fastapi-app:latest