name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Asdqwe!23
          POSTGRES_DB: fastapi_users
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL..."
          sleep 10

      - name: Create DB tables
        run: python -c "from database import create_db_and_tables; create_db_and_tables()"

      - name: Run tests
        env:
          DATABASE_URL: sqlite:///./test.db
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          SECRET_KEY: your-super-secret-key
        run: |
          pytest

      - name: Build Docker image
        run: |
          docker build . -t fastapi-app:latest